/*
 * TracerForm.java
 *
 * Created on 21 March 2007, 19:49
 */

package tracer.forms;


import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.Properties;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.ToolTipManager;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.BadLocationException;
import tracer.tasks.DeleteFile;
import tracer.tasks.LoadFileTask;
import tracer.tasks.MMCFGInitializer;
import tracer.tasks.WordSearcher;

/**
 *
 * @author  Admin
 */
public class TracerForm extends javax.swing.JFrame {
    
    private boolean needToScrolldown = true;
    private boolean isCapturingScroll = false;
       
    /** Creates new form TracerForm */
    public TracerForm() throws ClassNotFoundException {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (InstantiationException ex) {
            Logger.getLogger(TracerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TracerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TracerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadProperties();
        initComponents();
        initVars();

        jTraceTextArea.addMouseWheelListener(new MouseWheelListener() {
            public void mouseWheelMoved(MouseWheelEvent e) {
                vbar.dispatchEvent(e);
                adjustScroller();
            }
        });
        vbar.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
            }
            public void mousePressed(MouseEvent e) {
                isCapturingScroll = true;
            }
            public void mouseReleased(MouseEvent e) {
                isCapturingScroll = false;
            }
            public void mouseEntered(MouseEvent e) {
            }
            public void mouseExited(MouseEvent e) {
            }
        });

        vbar.addAdjustmentListener(new AdjustmentListener() {
            public void adjustmentValueChanged(AdjustmentEvent e) {
                if (isCapturingScroll) {
                    adjustScroller();
                }
            }
        });
    }

    private void adjustScroller() {
        int sum = vbar.getValue() + vbar.getVisibleAmount();
        int am = vbar.getMaximum();
        if (sum >= am) {
            //System.out.println("max!");
            needToScrolldown = true;
        } else {
            //System.out.println("no!");
            needToScrolldown = false;
        }
    }

    private LoadFileTask createLoadTimerTask() {
        return new LoadFileTask(fileName, maxNumLines, maxNumLinesEnabled, isUTF, this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionsDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jFontNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFontSizeTextField = new javax.swing.JTextField();
        jWarnLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jFlashLogTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jUTFCheckBox = new javax.swing.JCheckBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jNumLinesEnabledCheckBox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jNumLinesTextField = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jRestoreCheckBox = new javax.swing.JCheckBox();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jHTMLCheckBox = new javax.swing.JCheckBox();
        jOKButton = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jAutorefreshCheckBox = new javax.swing.JCheckBox();
        jWordWrapCheckbox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTraceTextArea = new javax.swing.JTextArea();
        jClearTraceButton = new javax.swing.JButton();
        jOnTopCheckbox = new javax.swing.JCheckBox();
        jOptionsButton = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jHighlightAllCheckbox = new javax.swing.JCheckBox();
        jFilterCheckbox = new javax.swing.JCheckBox();
        jMultipleLabel = new javax.swing.JLabel();
        jSearchTextField = new javax.swing.JTextField();
        jClearSearchButton = new javax.swing.JButton();
        jSearchWarnLabel = new javax.swing.JLabel();

        jOptionsDialog.setTitle("Options");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Font:");

        jLabel3.setText("Font size:");

        jWarnLabel.setFont(new java.awt.Font("Tahoma", 1, 11));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFontNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jWarnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jFontSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFontSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFontNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWarnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("flashlog.txt location:");

        jUTFCheckBox.setText("read file as UTF-8");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFlashLogTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(jUTFCheckBox)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jUTFCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFlashLogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jNumLinesEnabledCheckBox.setText("Load limited amount of bytes only");
        jNumLinesEnabledCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jNumLinesEnabledCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jNumLinesEnabledCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumLinesEnabledCheckBoxActionPerformed(evt);
            }
        });
        jNumLinesEnabledCheckBox.setBounds(10, 10, 370, 15);
        jLayeredPane1.add(jNumLinesEnabledCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("<html>This is usually required when your log file gets too big and Tracer crashes.</html>");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setBounds(10, 30, 370, 30);
        jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Max amount of bytes to load:");
        jLabel8.setBounds(10, 70, 370, 14);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jNumLinesTextField.setBounds(10, 90, 140, 20);
        jLayeredPane1.add(jNumLinesTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRestoreCheckBox.setText("Restore window on trace update if minimized");
        jRestoreCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRestoreCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRestoreCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestoreCheckBoxActionPerformed(evt);
            }
        });
        jRestoreCheckBox.setBounds(10, 10, 370, 15);
        jLayeredPane2.add(jRestoreCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jHTMLCheckBox.setText("Render log text as html");
        jHTMLCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jHTMLCheckBox.setEnabled(false);
        jHTMLCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jHTMLCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHTMLCheckBoxActionPerformed(evt);
            }
        });
        jHTMLCheckBox.setBounds(10, 10, 370, 15);
        jLayeredPane3.add(jHTMLCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jOKButton.setText("OK");
        jOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("<html><a href=\"http://google.com\">Check for updates...</a></html>");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.setBounds(10, 10, 370, 14);
        jLayeredPane5.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jOptionsDialogLayout = new javax.swing.GroupLayout(jOptionsDialog.getContentPane());
        jOptionsDialog.getContentPane().setLayout(jOptionsDialogLayout);
        jOptionsDialogLayout.setHorizontalGroup(
            jOptionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOptionsDialogLayout.createSequentialGroup()
                .addGroup(jOptionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jOptionsDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jOptionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                    .addGroup(jOptionsDialogLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jOKButton)))
                .addContainerGap())
        );
        jOptionsDialogLayout.setVerticalGroup(
            jOptionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOptionsDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jOKButton)
                .addGap(7, 7, 7))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flash Tracer");

        jAutorefreshCheckBox.setSelected(true);
        jAutorefreshCheckBox.setText("Autorefresh");
        jAutorefreshCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jAutorefreshCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jAutorefreshCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAutorefreshCheckboxChecked(evt);
            }
        });

        jWordWrapCheckbox.setSelected(true);
        jWordWrapCheckbox.setText("Word Wrap");
        jWordWrapCheckbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jWordWrapCheckbox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jWordWrapCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWordWrapCheckboxChecked(evt);
            }
        });

        jTraceTextArea.setColumns(20);
        jTraceTextArea.setFont(new java.awt.Font("Courier New", 0, 12));
        jTraceTextArea.setLineWrap(true);
        jTraceTextArea.setRows(5);
        jTraceTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTraceTextAreaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTraceTextArea);

        jClearTraceButton.setText("Clear");
        jClearTraceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jOnTopCheckbox.setText("Always On Top");
        jOnTopCheckbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jOnTopCheckbox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jOnTopCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOnTopCheckboxChecked(evt);
            }
        });

        jOptionsButton.setText("Options...");
        jOptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOptionsButtonActionPerformed(evt);
            }
        });

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jHighlightAllCheckbox.setText("Highlight All");
        jHighlightAllCheckbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jHighlightAllCheckbox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jHighlightAllCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHighlightAllCheckboxChecked(evt);
            }
        });
        jHighlightAllCheckbox.setBounds(10, 20, 73, 15);
        jLayeredPane4.add(jHighlightAllCheckbox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jFilterCheckbox.setText("Filter");
        jFilterCheckbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jFilterCheckbox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jFilterCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFilterCheckboxChecked(evt);
            }
        });
        jFilterCheckbox.setBounds(100, 20, 41, 15);
        jLayeredPane4.add(jFilterCheckbox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMultipleLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        jMultipleLabel.setText("Use , to filter multiple phrases");
        jMultipleLabel.setBounds(160, 20, 143, 14);
        jLayeredPane4.add(jMultipleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSearchTextField.setToolTipText("Hit enter to start searching");
        jSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchTextFieldActionPerformed(evt);
            }
        });
        jSearchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSearchTextFieldFocusLost(evt);
            }
        });
        jSearchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldKeyReleased(evt);
            }
        });
        jSearchTextField.setBounds(10, 40, 370, 20);
        jLayeredPane4.add(jSearchTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jClearSearchButton.setFont(new java.awt.Font("Tahoma", 0, 9));
        jClearSearchButton.setText("Clear Search");
        jClearSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearSearchButtonActionPerformed(evt);
            }
        });
        jClearSearchButton.setBounds(390, 40, 87, 21);
        jLayeredPane4.add(jClearSearchButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSearchWarnLabel.setText("<html></html>");
        jSearchWarnLabel.setBounds(10, 65, 580, 16);
        jLayeredPane4.add(jSearchWarnLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jAutorefreshCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWordWrapCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOnTopCheckbox)
                        .addGap(18, 18, 18)
                        .addComponent(jClearTraceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addComponent(jOptionsButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOptionsButton)
                    .addComponent(jAutorefreshCheckBox)
                    .addComponent(jWordWrapCheckbox)
                    .addComponent(jOnTopCheckbox)
                    .addComponent(jClearTraceButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMMCFG() {
        MMCFGInitializer i = new MMCFGInitializer();
        i.init();

        if (i.getTraceFileLocation() != null) {
            fileName = i.getTraceFileLocation();
        }
    }

    private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKButtonActionPerformed
        boolean fontExists = false;
        try {
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Font[] allfonts = env.getAllFonts();
            for (Font font : allfonts) {
                if (font.getName().equals(jFontNameTextField.getText())) {
                    fontExists = true;
                    break;
                }
            }
            if (fontExists) {
                setTraceFont(jFontNameTextField.getText(), jFontSizeTextField.getText());
                jWarnLabel.setText("");
                jOptionsDialog.setVisible(false);
            } else {
                jWarnLabel.setText("No such font!");
            }
            
            if (!fileName.equals(jFlashLogTextField.getText())) {
                setFlashLogFile(jFlashLogTextField.getText());
                jTraceTextArea.setText("");
            }

            setMaxNumLinesEnabled(jNumLinesEnabledCheckBox.isSelected());
            setMaxNumLines(jNumLinesTextField.getText());
            setUTF(jUTFCheckBox.isSelected());
            
            setAutoRefresh(jAutorefreshCheckBox.isSelected());

            setAlwaysOnTop(jOnTopCheckbox.isSelected());

            setRestoreOnUpdate(jRestoreCheckBox.isSelected());
            
        } catch (Exception ex) {
            
        }
        
    }//GEN-LAST:event_jOKButtonActionPerformed

    private void jOptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOptionsButtonActionPerformed
        if (jOnTopCheckbox.isSelected()) {
            setAlwaysOnTop(false);
        }
        jFontNameTextField.setText(jTraceTextArea.getFont().getName());
        jFontSizeTextField.setText(String.valueOf(jTraceTextArea.getFont().getSize()));
        jFlashLogTextField.setText(fileName);
        jRestoreCheckBox.setSelected(restoreOnUpdate);
        jOptionsDialog.setVisible(true);
        jNumLinesEnabledCheckBox.setSelected(maxNumLinesEnabled);
        jNumLinesTextField.setText(String.valueOf(maxNumLines));
    }//GEN-LAST:event_jOptionsButtonActionPerformed

    private void jFilterCheckboxChecked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFilterCheckboxChecked
        setFiltering(jFilterCheckbox.isSelected());
    }//GEN-LAST:event_jFilterCheckboxChecked

    private void jSearchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSearchTextFieldFocusLost
    }//GEN-LAST:event_jSearchTextFieldFocusLost

    private void jOnTopCheckboxChecked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOnTopCheckboxChecked
//        saveSetting("alwaysontop", String.valueOf(jOnTopCheckbox.isSelected()));
        setOnTop(jOnTopCheckbox.isSelected());
    }//GEN-LAST:event_jOnTopCheckboxChecked

    private void jHighlightAllCheckboxChecked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHighlightAllCheckboxChecked
        //saveSetting("highlight_all", String.valueOf(jHighlightAllCheckbox.isSelected()));
        setHighlightAll(jHighlightAllCheckbox.isSelected());
    }//GEN-LAST:event_jHighlightAllCheckboxChecked

    private void jClearSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearSearchButtonActionPerformed
        searcher.clearHighlights();
        searcher.setWasSearching(false);
        jSearchTextField.setText("");
        jSearchWarnLabel.setVisible(false);
    }//GEN-LAST:event_jClearSearchButtonActionPerformed
    
    private void jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyReleased
        if (jSearchTextField.getText().equals("")) {
            searcher.clearHighlights();
            searcher.setWasSearching(false);
            jSearchTextField.setText("");
            jSearchWarnLabel.setVisible(false);
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searcher.setWasSearching(true);
            startSearch(true);
        } else {
              ToolTipManager.sharedInstance().mouseMoved(
              new MouseEvent(jSearchTextField, 0, 0, 0,
                        (int) jSearchTextField.getCaret().getMagicCaretPosition().getX(), -jSearchTextField.getY(), // X-Y of the mouse for the tool tip
                        0, false));
        }
        
    }//GEN-LAST:event_jTextFieldKeyReleased
    
    private void jWordWrapCheckboxChecked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWordWrapCheckboxChecked
        setWordWrap(jWordWrapCheckbox.isSelected());
    }//GEN-LAST:event_jWordWrapCheckboxChecked
    
    private void jAutorefreshCheckboxChecked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAutorefreshCheckboxChecked
        setAutoRefresh(jAutorefreshCheckBox.isSelected());
    }//GEN-LAST:event_jAutorefreshCheckboxChecked
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        new DeleteFile(fileName);
        jTraceTextArea.setText("");
    }//GEN-LAST:event_deleteActionPerformed

    private void jNumLinesEnabledCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumLinesEnabledCheckBoxActionPerformed
        if (jNumLinesEnabledCheckBox.isSelected()) {
            long n = Long.parseLong(jNumLinesTextField.getText());
            if (!(n > 0)) {
                jNumLinesTextField.setText("1000");
            }
        }
}//GEN-LAST:event_jNumLinesEnabledCheckBoxActionPerformed

    private void jHTMLCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHTMLCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jHTMLCheckBoxActionPerformed

    private void jRestoreCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestoreCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRestoreCheckBoxActionPerformed

    private void jTraceTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTraceTextAreaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            if (jTraceTextArea.getSelectedText() != null && jTraceTextArea.getSelectedText().length() > 0) {
                jSearchTextField.setText(jTraceTextArea.getSelectedText());
            }
            searcher.setWasSearching(true);
            startSearch(true);
        }
}//GEN-LAST:event_jTraceTextAreaKeyPressed

    private void jSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchTextFieldActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            try {
                Desktop.getDesktop().browse(new URI("http://code.google.com/p/flash-tracer/downloads/list"));
            } catch (IOException ex) {
                Logger.getLogger(TracerForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(TracerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //String file = null;
        if (args.length > 0) {
            TracerForm.fileName = args[0];
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TracerForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TracerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void onOutOfMemory() {
        setMaxNumLinesEnabled(true);
        setMaxNumLines("100000");

        startTimer();

        JOptionPane pane = new JOptionPane();
        pane.showMessageDialog(this, "The log file is too big and our of memory error occured. Tracer has changed your settings to limit file " +
                "to 100 KB. Please change this value if needed in Options panel.", "Error", 1);
    }
    
    public void onFileRead(String inputFileBuff) {
        traceContent = inputFileBuff;
         
        if (restoreOnUpdate && traceIsModified()) {
            setExtendedState(JFrame.NORMAL);
        }
        recentTraceContent = traceContent;
        /*
        boolean needToScrolldown = false;
        int sum = vbar.getValue() + vbar.getVisibleAmount();
        int am = vbar.getMaximum();
        if (sum >= am) {
            needToScrolldown = true;
        } else {
            //System.out.println("sum=" + sum + ", scroll=" + am + ", ex=" + vbar.getVisibleAmount());
        }
        */
        //System.out.println("h= " + jTraceTextArea.getVisibleRect().getHeight());
        jTraceTextArea.setText(traceContent);
        
        traceLinesCount = jTraceTextArea.getLineCount();
        
        if (searcher.isWasSearching()) {
            startSearch(searcher.getLastCaretPos() - 1, false);
        }


        if (needToScrolldown) {
        
              jTraceTextArea.setCaretPosition( jTraceTextArea.getDocument().getLength() );


            
        }
        
    }

    private void setHTMLRender(boolean equals) {
        //jTraceTextArea.set = equals;
    }

    private void setMaxNumLinesEnabled(boolean equals) {
        jNumLinesEnabledCheckBox.setSelected(equals);
        maxNumLinesEnabled = equals;
    }

    private void setUTF(boolean equals) {
        isUTF = equals;
        jUTFCheckBox.setSelected(equals);
    }
    
    private void startTimer() {
        stopTimer();
        t = new Timer();
        t.schedule(createLoadTimerTask(), 1000, new Long(1000));
    }
    
    private void stopTimer() {
        if (t != null) {
            t.cancel();
        }
    }
   
    private void startSearch(int lastCarPos, boolean forcedScroll) {
        String word = jSearchTextField.getText();
        if (searcher.isFilter()) {
            try {
                jTraceTextArea.setText(searcher.filter(traceContent, word, traceLinesCount));
            } catch (Exception ex) {
            }
            jSearchWarnLabel.setVisible(false);
        } else {
            int offset = searcher.search(traceContent, word, lastCarPos);
            if (offset != -1) {
                jSearchWarnLabel.setVisible(true);
                jSearchWarnLabel.setText("<html>Result: <font color=\"blue\"><b>" + word + "</b></font> found!</html>");
                if (forcedScroll) {
                    try {
                        jTraceTextArea.scrollRectToVisible(jTraceTextArea
                                .modelToView(offset));
                        searcher.setLastCaretPos(offset + 1);
                    } catch (BadLocationException e) {
                    }
                }

            } else {
                searcher.setLastCaretPos(0);
                jSearchWarnLabel.setVisible(true);
                jSearchWarnLabel.setText("<html>Result: <font color=\"red\"><b>" + word + "</b></font> not found!</html>");
            }
        }
        
    }

    private void startSearch(boolean forcedScroll) {
        startSearch(searcher.getLastCaretPos(), forcedScroll);
    }
    
    private void startSearch() {
        startSearch(true);
    }

    private void initVars() {
        this.vbar = jScrollPane1.getVerticalScrollBar();
        this.searcher = new WordSearcher(jTraceTextArea);
        
        jOptionsDialog.setVisible(false);
        jOptionsDialog.setModal(true);
        jOptionsDialog.pack();
        
        //Get the screen size 
        Toolkit toolkit = Toolkit.getDefaultToolkit(); 
        Dimension screenSize = toolkit.getScreenSize(); 

        //Calculate the frame location 
        int x = (screenSize.width - getWidth()) / 2 + jOptionsDialog.getWidth()/2; 
        int y = (screenSize.height - getHeight()) / 2 + jOptionsDialog.getHeight()/2; 

        //Set the new frame location 
        jOptionsDialog.setLocation(x, y);


        setFlashLogFile(props.getProperty("settings.filename", ""));

        
        //setHTMLRender(props.getProperty("settings.html", "false").equals("true"));
        setUTF(props.getProperty("settings.isUTF", "true").equals("true"));
        setMaxNumLinesEnabled(props.getProperty("settings.maxNumLinesEnabled", "false").equals("true"));
        setMaxNumLines(props.getProperty("settings.maxNumLines", "1000"));
        setRestoreOnUpdate(props.getProperty("settings.restore", "false").equals("true"));
        setOnTop(props.getProperty("settings.alwaysontop", "false").equals("true"));
        setHighlightAll(props.getProperty("settings.highlight_all", "false").equals("true"));
        setAutoRefresh(props.getProperty("settings.autorefresh", "true").equals("true"));
        setWordWrap(props.getProperty("settings.wordwrap", "true").equals("true"));
        setFiltering(props.getProperty("settings.filter", "false").equals("true"));
        setTraceFont(props.getProperty("settings.font.name", "Courier New"), props.getProperty("settings.font.size", "12"));
        setDialogLocation(props.getProperty("settings.window.x", String.valueOf(this.getX())),
                props.getProperty("settings.window.y", String.valueOf(this.getY())),
                props.getProperty("settings.window.width", String.valueOf(this.getWidth())),
                props.getProperty("settings.window.height", String.valueOf(this.getHeight())));
        jMainFrame = this;
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(WindowEvent winEvt) {
                saveSetting("isUTF", String.valueOf(isUTF));
                saveSetting("autorefresh", String.valueOf(jAutorefreshCheckBox.isSelected()));
                saveSetting("alwaysontop", String.valueOf(jOnTopCheckbox.isSelected()));
                saveSetting("highlight_all", String.valueOf(jHighlightAllCheckbox.isSelected()));
                saveSetting("wordwrap", String.valueOf(jWordWrapCheckbox.isSelected()));
                saveSetting("filter", String.valueOf(jFilterCheckbox.isSelected()));
                saveSetting("font.name", jTraceTextArea.getFont().getName());
                saveSetting("font.size", String.valueOf(jTraceTextArea.getFont().getSize()));
                saveSetting("filename", fileName);
                saveSetting("window.x", String.valueOf(jMainFrame.getX()));
                saveSetting("window.y", String.valueOf(jMainFrame.getY()));
                saveSetting("window.width", String.valueOf(jMainFrame.getWidth()));
                saveSetting("window.height", String.valueOf(jMainFrame.getHeight()));
                saveSetting("restore", String.valueOf(restoreOnUpdate));
                saveSetting("maxNumLines", String.valueOf(maxNumLines));
                saveSetting("maxNumLinesEnabled", String.valueOf(maxNumLinesEnabled));
                //saveSetting("html", String.valueOf(jTraceTextArea.));
                try {
                    props.store(new FileOutputStream(settingsFile), "");
                } catch (FileNotFoundException ex) {
                    System.err.println("error saving setting 1.");
                } catch (IOException ex) {
                    System.err.println("error saving setting 2.");
                }
            }
        });
        
        createLoadTimerTask().run();
    }
    
    

    private void loadProperties() {
        props = new Properties();
        try {
            //throw new FileNotFoundException("dsfs");
            props.load(new FileInputStream(new File("tracer.properties")));
        } catch (FileNotFoundException ex) {
            initMMCFG();
        } catch (IOException ex) {
            
        }
    }

    private void saveSetting(String key, String val) {
        props.setProperty("settings." + key, val);
    }
    
    public void setOnTop (boolean b) {
        
        jOnTopCheckbox.setSelected(b);
        setAlwaysOnTop(b);
    }

    private void setHighlightAll(boolean b) {
        jHighlightAllCheckbox.setSelected(b);
        searcher.setHighlightAll(b);
    }

    private void setWordWrap(boolean b) {
        jWordWrapCheckbox.setSelected(b);
        this.jTraceTextArea.setLineWrap(b);
    }

    private void setAutoRefresh(boolean b) {
        jAutorefreshCheckBox.setSelected(b);
        isAutoRefresh = b;

        stopTimer();
        if (b) {
            startTimer();
        } 

    }

    private void setFiltering(boolean b) {
        jFilterCheckbox.setSelected(b);
        jMultipleLabel.setVisible(b);
        searcher.setIsFilter(b);
        jHighlightAllCheckbox.setEnabled(!b);
        if (jSearchTextField.getText() != null && jSearchTextField.getText().length() > 0) {
            startSearch();
        } 
    }

    private void setTraceFont(String name, String size) {
        jTraceTextArea.setFont(new Font(name, 0, Integer.parseInt(size)));
    }

    private void setFlashLogFile(String filen) {
        if (!filen.equals("")) {
            fileName = filen;
        }
    }
    
    private void setMaxNumLines(String lines) {
        maxNumLines = Long.valueOf(lines);
        jNumLinesTextField.setText(String.valueOf(maxNumLines));
    }

    private void setDialogLocation(String x, String y, String w, String h) {
        this.setLocation(Integer.parseInt(x), Integer.parseInt(y));
        this.setSize(Integer.parseInt(w), Integer.parseInt(h));
    }

    private boolean traceIsModified() {
        return !traceContent.equals(recentTraceContent);
    }

    private void setRestoreOnUpdate(boolean b) {
        jRestoreCheckBox.setSelected(b);
        restoreOnUpdate = b;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jAutorefreshCheckBox;
    private javax.swing.JButton jClearSearchButton;
    private javax.swing.JButton jClearTraceButton;
    private javax.swing.JCheckBox jFilterCheckbox;
    private javax.swing.JTextField jFlashLogTextField;
    private javax.swing.JTextField jFontNameTextField;
    private javax.swing.JTextField jFontSizeTextField;
    private javax.swing.JCheckBox jHTMLCheckBox;
    private javax.swing.JCheckBox jHighlightAllCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLabel jMultipleLabel;
    private javax.swing.JCheckBox jNumLinesEnabledCheckBox;
    private javax.swing.JTextField jNumLinesTextField;
    private javax.swing.JButton jOKButton;
    private javax.swing.JCheckBox jOnTopCheckbox;
    private javax.swing.JButton jOptionsButton;
    private javax.swing.JDialog jOptionsDialog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox jRestoreCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JLabel jSearchWarnLabel;
    private javax.swing.JTextArea jTraceTextArea;
    private javax.swing.JCheckBox jUTFCheckBox;
    private javax.swing.JLabel jWarnLabel;
    private javax.swing.JCheckBox jWordWrapCheckbox;
    // End of variables declaration//GEN-END:variables
    
    private Timer t;
    
    private WordSearcher searcher;

    public static String fileName = "flashlog.txt";

    private long maxNumLines = 20;

    private boolean maxNumLinesEnabled = false;

    private boolean isUTF = true;

    private JScrollBar vbar;
    
    private String traceContent;

    private boolean isAutoRefresh = true;

    private Properties props;

    private File settingsFile = new File("tracer.properties");

    private int traceLinesCount;

    private TracerForm jMainFrame;

    private String recentTraceContent;

    private boolean restoreOnUpdate = false;
    
}
